name: Hola 🖤

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hola, gracias for your proposed contribution to improve our 6-Figure Tech Writer Resource Hub. 🖤"
        pr-message: "Hola, gracias for creating your first pull request! 🖤"
